### ISSUE TITLE
Improve git completion (cannot type out commit hash)

### ISSUE THREAD

**Issue by petertriho** [petertriho/cmp-git#29]
At the moment, we can only manually select the git commit, typing out the hash (after `:`) does not work

**Comment by ner0-m** [comment]
Would you expect that to happen? If the completion is not specifically accepted, is a completion event even triggered?

Just looking at [cmp-spell](https://github.com/f3fora/cmp-spell), it also doesn't automatically replace my typos. I'm just not sure how this should be done.

**Comment by petertriho** [comment]
I haven't investigated this yet, but I think just adding the git commit trigger (`!`) in front of the hash will allow us to type out the hash
