### ISSUE TITLE
Rename source from `cmp_git` to `git`

### ISSUE THREAD

**Issue by petertriho** [petertriho/cmp-git#32]
Probably not even worth doing as this a breaking change with no value added.

Making this customizable through the config might be worth considering though

**Comment by hrsh7th** [comment]
You can register both name for avoiding breaking change gracefully.

**Comment by petertriho** [comment]
Would this work without issues?

```
M.setup = function(overrides)
	local source = Source.new(overrides)
    require("cmp").register_source("cmp_git", source)
	require("cmp").register_source("git", source)
end
```

**Comment by hrsh7th** [comment]
```
        require("cmp").register_source("cmp_git", Source.new(overrides))
	require("cmp").register_source("git", Source.new(overrides))
```
It should be the above.

It would be good to display deprecation warning if the user uses the `cmp_git` side.

**Comment by petertriho** [comment]
Source name changed to `git`

```
require("cmp").setup({
    sources = {
        { name = "git" },
        -- more sources
    }
})
```
