### ISSUE TITLE
Problem getting GitLab data

### ISSUE THREAD

**Issue by aaronclimbs** [petertriho/cmp-git#33]
I'm getting the below error when trying to complete both issues and MRs. Both users and commits complete fine, but when I use the `!` or `#` triggers, the below error is thrown.

```
Error executing vim.schedule lua callback: ...vim/site/pack/packer/start/cmp-git/lua/cmp-git/utils.lua:20: attempt to perform arithmetic on local 'hours' (a nil value)
```

I've tried running the mentioned function in the nvim console and I do get the expected output.
`:lua print(os.time())  // 1636683047`

**Comment by petertriho** [comment]
Can you see if that fixes it?

**Comment by petertriho** [comment]
I think it should be fixed now. Looks like gitlab supports two types of datetime strings

**Comment by aaronclimbs** [comment]
Sorry, I didn't get to this until now - interestingly, it works perfectly for me when I check out 20b7b8e, but not with the latest commit, 54d3fb6.

On the latest commit I get the below error:
```
Error executing vim.schedule lua callback: ...vim/site/pack/packer/start/cmp-git/lua/cmp_git/utils.lua:26: attempt to perform arithmetic on local 'hours' (a nil value)
stack traceback:
        ...vim/site/pack/packer/start/cmp-git/lua/cmp_git/utils.lua:26: in function 'parse_gitlab_date'
        ...im/site/pack/packer/start/cmp-git/lua/cmp_git/config.lua:70: in function 'get_sort_text'
        ...im/site/pack/packer/start/cmp-git/lua/cmp_git/gitlab.lua:195: in function 'handle_item'
        ...vim/site/pack/packer/start/cmp-git/lua/cmp_git/utils.lua:105: in function 'process_data'
        ...vim/site/pack/packer/start/cmp-git/lua/cmp_git/utils.lua:111: in function 'handle_response'
        ...im/site/pack/packer/start/cmp-git/lua/cmp_git/gitlab.lua:55: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

**Comment by petertriho** [comment]
@aaronclimbs Thanks! Looks like it I forgot to account for negative offset timezones

**Comment by aaronclimbs** [comment]
Working well for me now! Thanks!
