### ISSUE TITLE
Support custom label formats

### ISSUE THREAD

**Issue by b0o** [petertriho/cmp-git#36]
It would be nice to be able to control how labels are formatted. 
For example, I would like issues to display as:
                                                                                   
```
#12 [open]: Example issue title 1
#14 [closed]: Example issue title 2
```
                                                                                   
Perhaps a `format` option could be added to source configurations:
 
```lua                                                                                  
require('cmp_git').setup {
  github = {
    state = 'all',
    format = function(issue)
      return string.format('#%d: [%s] %s', issue.number, issue.state, issue.title)
    end
  }
}
```

**Comment by petertriho** [comment]
@b0o sorry this took long. I've added the ability for format the labels.

```
require('cmp_git').setup {
  github = {
    state = 'all',
    format = {
	  issues = {
        labels = function(trigger_char, issue)
		       		return string.format('#%d: [%s] %s', issue.number, issue.state, issue.title)
	  		     end
        }
	}
  }
}
```

**Comment by b0o** [comment]
This is great, thank you so much! One thing though, `issue` does not seem to have `state`, only these fields:

```
body
number
title
updatedAt
```

How could I get the issue state?

**Comment by petertriho** [comment]
Ah looks like I never added state to the `gh` cli request

```
❯ gh issue list --json
Specify one or more comma-separated fields for `--json`:
  assignees
  author
  body
  closed
  closedAt
  comments
  createdAt
  id
  labels
  milestone
  number
  projectCards
  reactionGroups
  state
  title
  updatedAt
  url
```

**Comment by petertriho** [comment]
I added state as default field, but you can change them under `config.github.issues.fields` and `config.github.pull_requests.fields`

**Comment by b0o** [comment]
Awesome, that works perfectly. Thank you again!
