### ISSUE TITLE
Not working through github CLI

### ISSUE THREAD

**Issue by nihilistkitten** [petertriho/cmp-git#39]
Apologies if this is documented somewhere.

For some reason, I can't get `cmp-git` to work with the official github CLI (e.x., for writing issues via `gh issue create`). By default, it sets its filetype to markdown. I've tried explicitly setting the filetype (by changing the editor command used by the CLI) to `markdown.github`, `github`, and `gitcommit`. Obviously for the former two I adjusted my config as follows:
```lua
require("cmp_git").setup({
	filetypes = { "gitcommit", "github" },
})
```
The filetype was getting properly set, and my `cmp-git` works in actual git commit messages.

**Comment by petertriho** [comment]
Are you logged into the gh cli? https://cli.github.com/manual/gh_auth_login

**Comment by nihilistkitten** [comment]
Thanks for the fast reply!

> Are you logged into the gh cli? 

Yes. My problem is that when creating or editing an issue via the CLI (`gh issue create`), which automatically opens the body of the issue for editing in my `$EDITOR`, `cmp-git` does not seem to be enabled.

> If you're writing issues, it might be worth trying out https://github.com/pwntester/octo.nvim

I think this solves an entirely different issue. I don't have any need for octo, which looks like a complete featureful github client inside of nvim; while it's cool that plugin exists, I prefer to exit to the CLI to interface with git/github. `cmp-git` gives me awesome completion features for git commit messages; all I want is to set up the same thing for github issue bodies from the github CLI.

**Comment by petertriho** [comment]
Ah ok, I see the issue. `cmp-git` is using the buffer's location to fetch issues (gh issue create creates a temp file user `/private/var/folders/...`). I'll see if I can fix this

**Comment by petertriho** [comment]
@nihilistkitten that should fix your issue (will still need to add `markdown` to the setup filetypes

**Comment by nihilistkitten** [comment]
Thank you! Seems to work. I have a related issue with filetypes, I'll open another issue.
