### ISSUE TITLE
Incorrect handling of dot-separated filetypes

### ISSUE THREAD

**Issue by nihilistkitten** [petertriho/cmp-git#40]
From `:h 'filetype'`:

> 	When a dot appears in the value then this separates two filetype
	names.  Example:
		/* vim: set filetype=c.doxygen : */ ~
	This will use the "c" filetype first, then the "doxygen" filetype.

The current filetype handling seems to be this line:

https://github.com/petertriho/cmp-git/blob/1961ee4ef59af5e58e96d54c78439aac11929e5d/lua/cmp_git/source.lua#L80

which just checks the entire filetype against the config. I think the correct behavior would be to split the filetype on `.` and check each such filetype against the config. I'm happy to write a PR for this.

I suspect this is not a very well-used feature, and it's hidden in a weird place in the help, so totally understand if you don't want to support this. My use-case is setting `ft=markdown.github` from the github CLI so I can have markdown support in that buffer (i.e., I can't just use `ft=github`) but don't need to turn on `cmp-git` for all markdown files (so I can't just use `ft=markdown`).

**Comment by petertriho** [comment]
Did not know about this. Definitely would love a PR for this. If it isn't a huge change, I'll try and and have it merged this week
