### ISSUE TITLE
issue with colon

### ISSUE THREAD

**Issue by AbhinavAchha** [petertriho/cmp-git#44]
after updating to latest commit I am facing this issue whenever i type or delete the colon (:)

> Error executing vim.schedule lua callback: ...im/site/pack/packer/start/cmp-git/lua/cmp_git/format.lua:141: attempt to index field 'format' (a nil value)
stack traceback:
        ...im/site/pack/packer/start/cmp-git/lua/cmp_git/format.lua:141: in function 'item'
        ...te/pack/packer/start/cmp-git/lua/cmp_git/sources/git.lua:126: in function 'cb'
        vim/_editor.lua:256: in function <vim/_editor.lua:256>

**Comment by petertriho** [comment]
Can you share your config? I don't have the issue on my machine

**Comment by AbhinavAchha** [comment]
Here is my config.
https://github.com/AbhinavAchha/neovim-config/main/lua/completion_git.lua

**Comment by petertriho** [comment]
Awesome
