### ISSUE TITLE
Bug: not completing at all & two cmp-git sources listed

### ISSUE THREAD

**Issue by chrisgrieser** [petertriho/cmp-git#47]
I do not get any completions anymore, not sure what happened.

When running `:CmpStatus`, I also noticed that cmp-git is listed *two* times, one of them always "unused", which might be related?

when in a gitcommit file:

<img width="50%" alt="image" src="https://user-images.githubusercontent.com/73286100/211175105-e5c57c48-387b-4943-89e3-2256277f87a5.png">

when in any other filetype:
<img width="50%" alt="image" src="https://user-images.githubusercontent.com/73286100/211175144-e00b38cd-0eda-4bbb-a801-c81063f012a0.png">

my full config:
```lua
cmp.setup.filetype("gitcommit", {
	sources = cmp.config.sources {
		{name = "git"},
	},
})
require("cmp_git").setup()
```

**Comment by chrisgrieser** [comment]
also, I just tried it: every source other than cmp-git works in gitcommits. I can even get gitcommit to work in all other filetypes, e.g. git completions do show up in lua, for example, when I add it as filetype. gitcommits are the only filetype where cmp-git does not work 🙈

**Comment by petertriho** [comment]
The two sources appearing is correct as I made a change in the past to support both `cmp-git` and `git` names (they both will appear as `cmp_git` under CmpStatus, just changed this to `git`)

As for completion not showing up, can you check "set filetype?" in the nvim commandline? 

When you added lua, did it look like the following?

```lua
require("cmp_git").setup({
    filetypes = { "gitcommit", "lua" },
})
```

**Comment by chrisgrieser** [comment]
> When you added lua, did it look like the following?
> 
> ```lua
> require("cmp_git").setup({
>     filetypes = { "gitcommit", "lua" },
> })
> ```

yes

> As for completion not showing up, can you check :set filetype? in the nvim commandline?

filetype is `gitcommit`, as it should be

**Comment by petertriho** [comment]
Does `:lua print(require("cmp_git.utils").is_git_repo())` return true?

**Comment by chrisgrieser** [comment]
ah, I think we are getting closer. I am in a git repo, but the command still returns false.
<img width="905" alt="Pasted image 2023-01-08 10 45 13" src="https://user-images.githubusercontent.com/73286100/211189591-9af904a4-b0cd-46f0-834d-b78c03236a18.png">

when I `:pwd` to check:
<img width="724" alt="Pasted image 2023-01-08 10 46 01" src="https://user-images.githubusercontent.com/73286100/211189604-ac31962e-ee5c-4070-ab21-790540605acd.png">

Now when I run `:cd ..` and run `....is_git_repo()` again, it does return true and also works 😅 

So I have set `autochdir` to true, which seems to be the cause of the issue. I tried setting it to false, and then everything worked fine.

**Comment by chrisgrieser** [comment]
okay, so a simple workaround that completely fixes the issue is to set an autocmd to move up:

```lua
vim.api.nvim_create_augroup("cmp-git-fix", {})
			vim.api.nvim_create_autocmd("FileType", {
				group = "cmp-git-fix",
				pattern = "gitcommit",
				command = "cd ./../"
			})
```

**Comment by petertriho** [comment]
Not sure if this is a fix as well but I found this https://stackoverflow.com/questions/27183726/autochdir-and-nerdtree

Recommends not using `autochdir` and using a autocmd instead

**Comment by chrisgrieser** [comment]
yep, an autocmd for that works as well. Since it seems to be an issue with more than one plugin, I guess that would be the best solution. 

Thanks for the assistance!

**Comment by petertriho** [comment]
@chrisgrieser Just pushed a fix. You should no longer require your workaround and I've removed the duplicate `cmp-git` source

**Comment by chrisgrieser** [comment]
Thank you!
