### ISSUE TITLE
Use with private Gitlab instance

### ISSUE THREAD

**Issue by CalebDW** [petertriho/cmp-git#49]
Hello! 

I would like to use this with my companies private gitlab instance, is that possible (or if not, could it the feature be added)? I imagine all it would need is the private url and corresponding token for the instance, so maybe a config `sources` table could be added with those keypairs?

Thanks!

**Comment by petertriho** [comment]
It should work if you have the private gitlab instance set up with https://gitlab.com/gitlab-org/cli or set `GITLAB_TOKEN`

**Comment by CalebDW** [comment]
So I've set the `GITLAB_TOKEN` for my own personal Gitlab account, but not sure that this can support multiple TOKENs?

**Comment by CalebDW** [comment]
Ah, the token just needs to be set on a per project basis. Sorry about that!
