### ISSUE TITLE
Support for Github Enterprise

### ISSUE THREAD

**Issue by sledigabel** [petertriho/cmp-git#50]
Private instances of Github Enterprise could also be supported natively.

The code in [github.lua](https://github.com/petertriho/cmp-git/blob/main/lua/cmp_git/sources/github.lua#L167) would exit immediately if the host is not `github.com`.
It would take a relatively small change to make this work as most of the framework would work fine (through the `gh` client).

As I can see it you could add a list of known private github urls in the conf and test this as part of the source.
The [fallback api endpoints](https://github.com/petertriho/cmp-git/blob/main/lua/cmp_git/sources/github.lua#L108) in case `gh` is missing would also need to be constructed a bit differently.

**Comment by petertriho** [comment]
Will try and add this and gitlab self-hosted over the weekend

**Comment by sledigabel** [comment]
@petertriho sorry I didn't see your comment today I hope the PR I filed is what you had in mind
