### ISSUE TITLE
BUG: attempt to call field 'contains' (a nil value)

### ISSUE THREAD

**Issue by Shinzu** [petertriho/cmp-git#52]
Hello,

in https://github.com/petertriho/cmp-git/blob/main/lua/cmp_git/sources/github.lua#L157 is the `table.contains` function used which throws an error than for me:

```
Error executing lua callback: ...l/share/nvim/lazy/cmp-git/lua/cmp_git/sources/gitlab.lua:60: attempt to call field 'contains' (a nil value)
```

i dont know if this is a custom function in your setup, but for me it does not work.

I replaced this then with `vim.tbl_contains` which works then for me.

**Comment by petertriho** [comment]
Thanks, should be fixed now

**Comment by Shinzu** [comment]
thx is working for me
